### ISSUE TITLE
Issues when lotus validations is used with lotus entity.

### ISSUE THREAD

**Issue by taylorfinnell** [lotus/model#203] opened 2015-07-02 15:39 UTC
It may not be exactly related to using validations but this code does not work as expected.

```ruby
require 'lotus/model'
require 'lotus/validations'

module Lotus
 module Auth0
    class User
      include ::Lotus::Entity 
      include ::Lotus::Validations 
      attribute :user_id, type: String, presence: true 
      attribute :name, type: String, presence: true 
      attribute :email, type: String, presence: true 
      attribute :password, type: String, presence: true 
      attribute :identities, type: Array, presence: true 

      def id
        self.user_id 
      end

      def id=(_id) 
        self.user_id = _id 
      end 
    end 
  end 
end

user = Lotus::Auth0::User.new(id: 'oauth2|moves|12345')
```

The first time user.user_id is the correct thing, the second time it is nil.

**Comment by taylorfinnell** [comment] 2015-07-03 00:33
This only happens if both modules are included. I think this issue should be in the validations repo and the failing test in the integration test that tests compatibility. Does that seem reasonable?

**Comment by jodosha** [comment] 2015-07-03 10:17
@taylorfinnell Thanks for reporting this. :+1: 

I can confirm the problem. It happens only when you override `id`, if try to do the same thing with `name` it works fine:

```ruby
require 'lotus/model'
require 'lotus/validations'

module Lotus
 module Auth0
    class User
      include ::Lotus::Entity 
      include ::Lotus::Validations 
      attribute :user_id, type: String, presence: true 
      attribute :name, type: String, presence: true 
      attribute :full_name, type: String, presence: true # NEW ATTRIBUTE
      attribute :email, type: String, presence: true 
      attribute :password, type: String, presence: true 
      attribute :identities, type: Array, presence: true 

      def id
        self.user_id 
      end

      def id=(_id) 
        self.user_id = _id 
      end 

      def name
        self.full_name
      end

      def name=(value)
        self.full_name = value
      end
    end 
  end 
end

user = Lotus::Auth0::User.new(id: 'oauth2|moves|12345', name: 'LG')
# => #<Lotus::Auth0::User:0x007fd35c499f08
 @attributes=#<Lotus::Utils::Attributes:0x007fd35c499ee0 @attributes={"user_id"=>"oauth2|moves|12345", "full_name"=>"LG", "id"=>"oauth2|moves|12345"}>>

user.name = 'MG'

user
=> #<Lotus::Auth0::User:0x007fd35c499f08
 @attributes=#<Lotus::Utils::Attributes:0x007fd35c499ee0 @attributes={"user_id"=>"oauth2|moves|12345", "full_name"=>"MG", "id"=>"oauth2|moves|12345"}>>

user.to_h
=> {:user_id=>"oauth2|moves|12345", :full_name=>"MG", :id=>"oauth2|moves|12345"}
```

I guess this is because `id` has a special handling. This is an edge case that we are happy that you have shared with us. Let me try to explain the complexity and how to reduce it or solve your problem.

  * Please don't use `Lotus` module, it's a fragile approach that can break your lib in the future.
  * `Lotus::Entity` and `Lotus::Validations` [weren't designed](http://lucaguidi.com/2014/10/23/introducing-lotus-validations.html) to work together. We're trying to make this possible, but it isn't what we suggest by default.
  * Why do you need to alias `id` with `user_id`? If your data source has that information, the mapper is the tool designed to solve this kind of situations. See the next snippet.

I assume that you storage has a kinda of schema that uses `user_id` as primary key, but for our sanity we want that our `User` entity will use `id` instead. Mapper is here for you :+1: 

```ruby
collection :users do
  # ...
  attribute :id, String, as: :user_id
end
```

This mapping will resolve the impedance between the entity and the database.

Does this approach solves your problem? Please let me know :smile:

**Comment by taylorfinnell** [comment] 2015-07-03 10:29
The mapper `as: ` looks like it will do exactly what I need, for the reason you mentioned. My storage uses `user_id` as the primary key and I want `id` for my sanity :). I have not tested yet but I think it will. For what it's worth I traced the issue to this line. https://github.com/taylorfinnell/validations/commit/ca7290211be3bdb3c1293b2863fd9f7b302978de. I have not had time to dig in to see what that line did or what it broke, but all the tests are passing. However, I think the mapper is the simpler solution. Thank you!

**Comment by jodosha** [comment] 2015-07-03 10:35
@taylorfinnell I'm closing this. Feel free to reopen in case you still have problems. Thank you :+1:

**Closed by jodosha** 2015-07-03 10:35 UTC
Labels: discussion
