### ISSUE TITLE
Map default value for entity

### ISSUE THREAD

**Issue by joneslee85** [lotus/model#189] opened 2015-05-28 23:08 UTC
If my column DB has a default value, should we pick this up when we define `attributes` for Entity?

Atm, ofcourse I could reader like this:

```
class MyEntity
  def my_value
    @my_value || "my default value"
  end
end
```

However I think we should provide automatic default value mapping. Thoughts?

cc @jodosha @AlfonsoUceda @solnic

**Comment by jodosha** [comment] 2015-06-03 09:44
Duplicate of #136

**Closed by jodosha** 2015-06-03 09:44 UTC
Labels: discussion
